CREATE DATABASE IF NOT EXISTS login_database
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE login_database;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    pass VARCHAR(255) NOT NULL
);